export const products = [
    {id:1,
     name:"Almond Milks",
     description: "Variety of almond milks",
     price: 200,
     category: "Vegans",
     quantity: 1,
     img: "lechesDeALMENDRAS.webp"
    },
    {id:2,
     name: "Berries",
     description: "Price per kilogram",
     price: 800,
     category: "Vegans",
     img: "frutosSecos.webp"},
     {id:3,
      name: "Lentils",
      description: "Price per kilogram",
      price: 270,
      img: "lentejas.webp"},
      {id:4,
      name: "Peanut Butter",
      description: "Peanut Butters of all tastes",
      price: 260,
      img: "MantequillaDeMani.webp"},
      {id:5,
       name: "Cornflakes",
      description: "Price per Quarter",
      price: 64,
      img: "coposdeMaiz.webp"},
      {id:6,
       name: "Vegan Cheese",
       description: "Without animal ingredients",
       price: 320,
       category: "Vegans",
       img: "FelicesLasVacas.png"},
       {id:7,
        name: "Celiac Bread",
        description: "Product for celiacs",
        price: 220,
        category: "Celiacs",
        img: "celiacos-pan.webp"},
        {id:8,
        name: "Celiac flour",
        description: "Product for celiacs",
        price: 250,
        category: "Celiacs",
        img: "shopping.png"}
] 