export const products = [
    {id:1,
     name:"Almond Milks",
     description: "Variety of almond milks",
     price: 200,
     category: "Vegans",
     img: "lechesDeALMENDRAS.webp"
    },
    {id:2,
     name: "Berries",
     description: "Price per kilogram",
     price: 800,
     category: "Vegans",
     img: "frutosSecos.webp"},
     {id:3,
      name: "Lentils",
      description: "Price per kilogram",
      price: 270,
      img: "lentejas.webp"},
      {id:4,
      name: "Peanut Butter",
      description: "Peanut Butters of all tastes",
      price: 260,
      img: "MantequillaDeMani.webp"},
      {id:5,
       name: "Cornflakes",
      description: "Price per Quarter",
      price: 64,
      img: "coposdeMaiz.webp"},
      {id:6,
       name: "Vegan Cheese",
       description: "Without animal ingredients",
       price: 320,
       category: "Vegans",
       img: "FelicesLasVacas.png"},
       {id:7,
        name: "Celiac Bread",
        description: "Product for celiacs",
        price: 220,
        category: "Celiacs",
        img: "celiacos-pan.webp"},
        {id:8,
        name: "Celiac flour",
        description: "Product for celiacs",
        price: 250,
        category: "Celiacs",
        img: "shopping.png"},
        {id:9,
        name: "Vegan Burgers",
        description: "The best Vegan Burgers",
        price: 290,
        category: "Vegans",
        img: "VeganBurger.png"},
        {id:10,
        name: "Vegan Hot Dogs",
        description: "Product for vegans",
        price: 300,
        category: "Vegans",
        img: "HotDog.webp"},
        {id:11,
        name: "Vegan Smoothie",
        description: "Product for Vegans",
        price: 230,
        category: "Vegans",
        img: "smoothies.jpg"},
        {id:12,
        name: "Celiac Cookies",
        description: "Product for celiacs",
        price: 120,
        category: "Celiacs",
        img: "CeliacCookies.png"},
        {id:13,
        name: "Celiac Cornflakes",
        description: "Product for celiacs",
        price: 280,
        category: "Celiacs",
        img: "Cornflakes.jpg"},
        {id:14,
        name: "Celiac Puddig",
        description: "Product for celiacs",
        price: 250,
        category: "Celiacs",
        img: "CeliacPudding.jpg"},
        {id:15,
        name: "Celiac Icecream",
        description: "Product for celiacs",
        price: 390,
        category: "Celiacs",
        img: "IceCream.png"}
] 